"""added amenity to farm

Revision ID: 0932f6697771
Revises: 
Create Date: 2021-07-05 23:04:32.887611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0932f6697771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('primaryImage', sa.String(), nullable=False),
    sa.Column('secondImage', sa.String(), nullable=True),
    sa.Column('thirdImage', sa.String(), nullable=True),
    sa.Column('fourthImage', sa.String(), nullable=True),
    sa.Column('fifthImage', sa.String(), nullable=True),
    sa.Column('farmName', sa.String(), nullable=True),
    sa.Column('farmId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('farmer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pricePerDay', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('primaryImage', sa.String(), nullable=False),
    sa.Column('secondImage', sa.String(), nullable=True),
    sa.Column('thirdImage', sa.String(), nullable=True),
    sa.Column('fourthImage', sa.String(), nullable=True),
    sa.Column('fifthImage', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('amenityId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goatYoga', sa.Boolean(), nullable=True),
    sa.Column('pigRoast', sa.Boolean(), nullable=True),
    sa.Column('tableMaking', sa.Boolean(), nullable=True),
    sa.Column('farmId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('costOfStay', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('startDate', sa.String(), nullable=False),
    sa.Column('endDate', sa.String(), nullable=False),
    sa.Column('farmId', sa.Integer(), nullable=False),
    sa.Column('numberOfGuests', sa.Integer(), nullable=False),
    sa.Column('nameOfFarm', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('amenities')
    op.drop_table('farms')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###
