"""booking includes farmName

Revision ID: cca12e72e3b9
Revises: 
Create Date: 2021-07-01 11:05:16.405964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca12e72e3b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('farmer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('cost_of_stay', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('start_day', sa.String(), nullable=False),
    sa.Column('end_day', sa.String(), nullable=False),
    sa.Column('farmId', sa.Integer(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('name_of_farm', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('farms')
    op.drop_table('users')
    # ### end Alembic commands ###
